### ISSUE TITLE
add 3rd party Styles

### ISSUE THREAD

**Issue by SdSalaat** [jurgelenas/pdfify-server#2]
How can we add 3rd party styles like bootstrap or something else when req is received through client

Any Solution for that

**Comment by ktthesilentkiller** [comment]
When ever i try to  run it its showing errors.


C:\Users\Admin\Downloads\pdfify-server-master\node_modules\.bin\forever:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdfify-server@1.0.0 start: `node ./node_modules/.bin/forever -m 5 server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdfify-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-16T07_49_34_981Z-debug.log

C:\Users\Admin\Downloads\pdfify-server-master>
